In [19]:
import pandas as pd

In [24]:
df = pd.read_csv("Resources/ufoSightings.csv")

C:\Users\julia\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [25]:
df2 = df.dropna(axis = 0, how = "any")

In [26]:
df.count()

datetime                80332
city                    80332
state                   74535
country                 70662
shape                   78400
duration (seconds)      80332
duration (hours/min)    80332
comments                80317
date posted             80332
latitude                80332
longitude               80332
dtype: int64

In [27]:
df2.count()

datetime                66516
city                    66516
state                   66516
country                 66516
shape                   66516
duration (seconds)      66516
duration (hours/min)    66516
comments                66516
date posted             66516
latitude                66516
longitude               66516
dtype: int64

In [47]:
group_df = df2.groupby(["country", "state"]).count()
group_df

               datetime  city  shape  duration (seconds)  \
country state
au      al            1     1      1                   1
        dc            1     1      1                   1
        nt            2     2      2                   2
        oh            1     1      1                   1
        sa            2     2      2                   2
        wa            2     2      2                   2
        yt            1     1      1                   1
ca      ab          284   284    284                 284
        bc          677   677    677                 677
        mb          124   124    124                 124
        nb           86    86     86                  86
        nf           15    15     15                  15
        ns          101   101    101                 101
        nt           13    13     13                  13
        on         1335  1335   1335                1335
        pe           10    10     10                  10
        pq           62    62     62                  62
        qc          124   124    124                 124
        sa           27    27     27                  27
        sk           77    77     77                  77
        yk            2     2      2                   2
        yt            5     5      5                   5
gb      bc            1     1      1                   1
        la            1     1      1                   1
        ms            1     1      1                   1
        nc            1     1      1                   1
        ns            2     2      2                   2
        nt            1     1      1                   1
        sk            1     1      1                   1
        tn            1     1      1                   1
...                 ...   ...    ...                 ...
us      mi         1781  1781   1781                1781
        mn          996   996    996                 996
        mo         1431  1431   1431                1431
        ms          368   368    368                 368
        mt          460   460    460                 460
        nc         1722  1722   1722                1722
        nd          123   123    123                 123
        ne          373   373    373                 373
        nh          482   482    482                 482
        nj         1236  1236   1236                1236
        nm          693   693    693                 693
        nv          778   778    778                 778
        ny         2915  2915   2915                2915
        oh         2251  2251   2251                2251
        ok          714   714    714                 714
        or         1667  1667   1667                1667
        pa         2319  2319   2319                2319
        pr           24    24     24                  24
        ri          224   224    224                 224
        sc          986   986    986                 986
        sd          177   177    177                 177
        tn         1091  1091   1091                1091
        tx         3398  3398   3398                3398
        ut          611   611    611                 611
        va         1248  1248   1248                1248
        vt          254   254    254                 254
        wa         3707  3707   3707                3707
        wi         1205  1205   1205                1205
        wv          438   438    438                 438
        wy          169   169    169                 169

               duration (hours/min)  comments  date posted  latitude  \
country state
au      al                        1         1            1         1
        dc                        1         1            1         1
        nt                        2         2            2         2
        oh                        1         1            1         1
        sa                        2         2            2         2
        wa                        2         2            2         2
        yt                        1         1            1         1
ca      ab                      284       284          284       284
        bc                      677       677          677       677
        mb                      124       124          124       124
        nb                       86        86           86        86
        nf                       15        15           15        15
        ns                      101       101          101       101
        nt                       13        13           13        13
        on                     1335      1335         1335      1335
        pe                       10        10           10        10
        pq                       62        62           62        62
        qc                      124       124          124       124
        sa                       27        27           27        27
        sk                       77        77           77        77
        yk                        2         2            2         2
        yt                        5         5            5         5
gb      bc                        1         1            1         1
        la                        1         1            1         1
        ms                        1         1            1         1
        nc                        1         1            1         1
        ns                        2         2            2         2
        nt                        1         1            1         1
        sk                        1         1            1         1
        tn                        1         1            1         1
...                             ...       ...          ...       ...
us      mi                     1781      1781         1781      1781
        mn                      996       996          996       996
        mo                     1431      1431         1431      1431
        ms                      368       368          368       368
        mt                      460       460          460       460
        nc                     1722      1722         1722      1722
        nd                      123       123          123       123
        ne                      373       373          373       373
        nh                      482       482          482       482
        nj                     1236      1236         1236      1236
        nm                      693       693          693       693
        nv                      778       778          778       778
        ny                     2915      2915         2915      2915
        oh                     2251      2251         2251      2251
        ok                      714       714          714       714
        or                     1667      1667         1667      1667
        pa                     2319      2319         2319      2319
        pr                       24        24           24        24
        ri                      224       224          224       224
        sc                      986       986          986       986
        sd                      177       177          177       177
        tn                     1091      1091         1091      1091
        tx                     3398      3398         3398      3398
        ut                      611       611          611       611
        va                     1248      1248         1248      1248
        vt                      254       254          254       254
        wa                     3707      3707         3707      3707
        wi                     1205      1205         1205      1205
        wv                      438       438          438       438
        wy                      169       169          169       169

               longitude
country state
au      al              1
        dc              1
        nt              2
        oh              1
        sa              2
        wa              2
        yt              1
ca      ab            284
        bc            677
        mb            124
        nb             86
        nf             15
        ns            101
        nt             13
        on           1335
        pe             10
        pq             62
        qc            124
        sa             27
        sk             77
        yk              2
        yt              5
gb      bc              1
        la              1
        ms              1
        nc              1
        ns              2
        nt              1
        sk              1
        tn              1
...                   ...
us      mi           1781
        mn            996
        mo           1431
        ms            368
        mt            460
        nc           1722
        nd            123
        ne            373
        nh            482
        nj           1236
        nm            693
        nv            778
        ny           2915
        oh           2251
        ok            714
        or           1667
        pa           2319
        pr             24
        ri            224
        sc            986
        sd            177
        tn           1091
        tx           3398
        ut            611
        va           1248
        vt            254
        wa           3707
        wi           1205
        wv            438
        wy            169

[84 rows x 9 columns]

In [37]:
print(type(group_df))

<class 'pandas.core.groupby.DataFrameGroupBy'>